/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import model.Notification;
import model.NotificationManager;

/**
 *
 * @author Rushma
 */
public class Notifications extends javax.swing.JFrame {

    public Notifications(int tutorId) {
        initComponents();
        loadNotifications(tutorId); // Pass the tutor ID (example: 1)
    }

    private Notifications() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void loadNotifications(int tutorId) {
    // Fetch notifications for the given tutor
    List<Notification> notifications = NotificationManager.getDailyNotifications(tutorId);

    // Clear the parent container
    notificationsPanel.removeAll();

    // Set layout for the notifications panel
    notificationsPanel.setLayout(new BoxLayout(notificationsPanel, BoxLayout.Y_AXIS));

    // If there are no notifications, show a default message
    if (notifications.isEmpty()) {
        JLabel noNotificationLabel = new JLabel("<html><b>No classes scheduled for today.</b></html>");
        notificationsPanel.add(noNotificationLabel);
    } else {
        for (Notification notification : notifications) {
            JPanel notificationBox = new JPanel();

            // Set the preferred size for the notification box
            notificationBox.setPreferredSize(new Dimension(400, 100)); // Wider and taller box
            notificationBox.setMaximumSize(new Dimension(400, 100)); // Ensure consistent size

            // Create a label for the notification details
            JLabel notificationLabel = new JLabel("<html>" + notification.getDetails() + "</html>");
            notificationLabel.setVerticalAlignment(SwingConstants.CENTER);

            // Create a "More Info" button
            JButton moreInfoButton = new JButton("More Info");

            // Add action listener to the More Info button
            moreInfoButton.addActionListener(e -> {
                System.out.println("Details for Class ID: " + notification.getClassId());
                new NotificationDetails(notification.getClassId()).setVisible(true);
            });

            // Add components to the notification box
            notificationBox.add(notificationLabel, BorderLayout.CENTER);
            notificationBox.add(moreInfoButton, BorderLayout.EAST);

            // Add the notification box to the parent panel
            notificationsPanel.add(notificationBox);
        }
    }

    // Refresh the parent container
    notificationsPanel.revalidate();
    notificationsPanel.repaint();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        notificationsPanel = new javax.swing.JPanel();
        detailsLabel = new javax.swing.JLabel();
        moreInfoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("Notifications");

        notificationsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        detailsLabel.setBackground(new java.awt.Color(204, 204, 204));
        detailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailsLabel.setText("notification here");
        detailsLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        moreInfoBtn.setText("More Info");
        moreInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreInfoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout notificationsPanelLayout = new javax.swing.GroupLayout(notificationsPanel);
        notificationsPanel.setLayout(notificationsPanelLayout);
        notificationsPanelLayout.setHorizontalGroup(
            notificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificationsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(moreInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(notificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificationsPanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(168, 168, 168)))
        );
        notificationsPanelLayout.setVerticalGroup(
            notificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificationsPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(moreInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(460, Short.MAX_VALUE))
            .addGroup(notificationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(notificationsPanelLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(detailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(449, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(492, 492, 492))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(notificationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(notificationsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void moreInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreInfoBtnActionPerformed
        int selectedClassId = 1; // Replace with logic to get the actual Class ID
        new NotificationDetails(selectedClassId).setVisible(true);
    }//GEN-LAST:event_moreInfoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatArcIJTheme.setup();

        java.awt.EventQueue.invokeLater(() -> new Notifications().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton moreInfoBtn;
    private javax.swing.JPanel notificationsPanel;
    // End of variables declaration//GEN-END:variables
}
