/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.MySQL2;

/**
 *
 * @author kalin
 */
public class StudentAttendanceCourse extends javax.swing.JFrame {

    /**
     * Creates new form StudentAttendanceCourse
     */
    public StudentAttendanceCourse() {
        initComponents();
        loadCourses();
    }
private StudentAttendanceClass attendanceClass;
   // Variable to keep track of the currently opened course ID
private int currentCourseId = 0;

private void loadCourses() {
    try {
        String query = "SELECT * FROM `courses`";

        // Execute SQL query to retrieve courses
        ResultSet rs = MySQL2.executeSearch(query);

        // Clear existing buttons
        jPanelCourses.removeAll();
        jPanelCourses.revalidate();
        jPanelCourses.repaint();

        // Iterate through the result set and create buttons
        while (rs.next()) {
            int courseId = rs.getInt("id");
            String courseName = rs.getString("name");

            // Create a new button for each course
            JButton courseButton = new JButton(courseName);
            courseButton.addActionListener(e -> {
                if (attendanceClass == null) {
                    // Check if the instance has not been created
                    attendanceClass = new StudentAttendanceClass(courseId); // Create a new instance
                    currentCourseId = courseId; // Set the current course ID
                } else if (!Integer.toString(courseId).equals(currentCourseId)) {
                    // If the course ID is different
                    attendanceClass.dispose(); // Close the current JFrame
                    attendanceClass = new StudentAttendanceClass(courseId); // Create a new instance for the new course ID
                    currentCourseId = courseId; // Update the current course ID
                }

                if (!attendanceClass.isVisible()) {
                    // Check if it's not visible
                    attendanceClass.setVisible(true); // Make it visible
                } else {
                    // Bring it to the front if it's already visible
                    attendanceClass.toFront();
                    attendanceClass.requestFocus();
                }
            });

            // Add the button to the JPanel
            jPanelCourses.add(courseButton);
        }

        // Refresh the JPanel to show the new buttons
        jPanelCourses.revalidate();
        jPanelCourses.repaint();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelCourses = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(825, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Select Course");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 19, -1, -1));
        getContentPane().add(jPanelCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, 825, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAttendanceCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAttendanceCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAttendanceCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAttendanceCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentAttendanceCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelCourses;
    // End of variables declaration//GEN-END:variables
}
