/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.MySQL2;

/**
 *
 * @author Rushma
 */
public class TutorCancelledSessions extends javax.swing.JPanel {
    private DashboardInterface parent;

    /**
     * Creates new form TutorCancelledSessions
     */
    public TutorCancelledSessions(DashboardInterface parent) {
        this.parent = parent;
        initComponents();
        loadCancelledSessions();

    }

    private void loadCancelledSessions() {
        try {
            // SQL query to fetch cancelled session details
            ResultSet resultSet = MySQL2.executeSearch(
                    "SELECT tutor_cancelled_sessions.id, courses.name AS course_name, "
                    + "tutor.first_name, tutor.last_name, class.name AS class_name, "
                    + "class.date, class.start_time, class.end_time, class.hallnumber, "
                    + "class.amount, class_status.name AS status_name, "
                    + "tutor_cancelled_sessions.reason "
                    + "FROM tutor_cancelled_sessions "
                    + "INNER JOIN class ON tutor_cancelled_sessions.class_id = class.id "
                    + "INNER JOIN tutor ON class.tutor_id = tutor.id "
                    + "INNER JOIN courses ON class.courses_id = courses.id "
                    + "INNER JOIN class_status ON class.class_status_id = class_status.id"
            );

            // Get the table model for jTable1 and clear previous data
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            // Iterate through the result set and add rows to the table
            while (resultSet.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("id")); // ID
                vector.add(resultSet.getString("course_name")); // Course Name
                vector.add(resultSet.getString("first_name") + " " + resultSet.getString("last_name")); // Tutor
                vector.add(resultSet.getString("class_name")); // Title
                vector.add(resultSet.getString("date")); // Date
                vector.add(resultSet.getString("start_time")); // Start Time
                vector.add(resultSet.getString("end_time")); // End Time
                vector.add(resultSet.getString("hallnumber")); // Hall Number
                vector.add(resultSet.getString("amount")); // Amount
                vector.add(resultSet.getString("status_name")); // Class Status
                vector.add(resultSet.getString("reason")); // Reason

                model.addRow(vector);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Cancelled Sessions");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Course Name", "Tutor", "Title", "Date", "Start Time", "End Time", "Hall Number", "Amount", "Class Status", "Reason"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 386, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 380, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
