/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.ResultSet;
import model.MySQL2;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author Rushma
 */
public class TutorDetails extends javax.swing.JFrame {
    private static final Logger logger = LogManager.getLogger(TutorDetails.class);

    public TutorDetails(int tutorId) {
        initComponents();
        System.out.println(tutorId);
        loadTutorDetails(tutorId);
    }

    public TutorDetails() {

    }

    private void loadTutorDetails(int tutorId) {
        try {
            // Query to fetch tutor details using inner joins
            String query = "SELECT t.nic, "
                    + "CONCAT(t.first_name, ' ', t.last_name) AS name, "
                    + "t.qualification, "
                    + "t.contact_info, "
                    + "g.name AS gender, " // Joining gender table
                    + "c.name AS courses " // Joining courses table
                    + "FROM tutor t "
                    + "INNER JOIN gender g ON t.gender_id = g.id " // Joining gender table
                    + "INNER JOIN courses c ON t.courses_id = c.id " // Joining courses table
                    + "WHERE t.id = " + tutorId;

            // Execute the query
            ResultSet rs = MySQL2.executeSearch(query);

            // If data is available, populate the labels
            if (rs.next()) {
                nicLabel.setText(rs.getString("nic"));
                nameLabel.setText(rs.getString("name"));
                qualificationLabel.setText(rs.getString("qualification"));
                contactLabel.setText(rs.getString("contact_info"));
                genderLabel.setText(rs.getString("gender"));
                courseLabel.setText(rs.getString("courses"));
            } else {
                // If no data is found, show a default message
                nameLabel.setText("No data found");
            }

            // Close the ResultSet
            rs.close();
        } catch (Exception e) {
            logger.error("Exception caught", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nicLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        qualificationLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        courseLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("Tutor Details");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Name :");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Qualification :");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Contact Information :");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Gender :");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel7.setText("NIC :");

        nicLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nicLabel.setText("NIC :");

        nameLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        nameLabel.setText("Name :");

        qualificationLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        qualificationLabel.setText("Qualification :");

        contactLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        contactLabel.setText("Contact Information :");

        genderLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        genderLabel.setText("Gender :");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel6.setText("Courses :");

        courseLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        courseLabel.setText("Gender :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nicLabel)
                    .addComponent(nameLabel)
                    .addComponent(qualificationLabel)
                    .addComponent(contactLabel)
                    .addComponent(genderLabel)
                    .addComponent(courseLabel))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(jLabel2))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qualificationLabel)
                    .addComponent(jLabel3))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactLabel)
                    .addComponent(jLabel4))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(jLabel5))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseLabel)
                    .addComponent(jLabel6))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nicLabel)
                    .addComponent(jLabel7))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorDetails().setVisible(true);  // Pass an actual employeeID
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nicLabel;
    private javax.swing.JLabel qualificationLabel;
    // End of variables declaration//GEN-END:variables
}